name: 'Terraform AWS Provider Team Stats'
description: 'Pulls useful info for use in reporting/slack/etc...'
inputs:
  token:
    description: 'A valid github token for the organization'
    required: true
outputs:
  stats:
    description: 'Number of open PRs per team member'
runs:
  using: 'node12'
  main: 'index.js'