name: 'Github Orgnization Team Member PR Summary'
description: 'Open PR counts for team members in specified org/team'
inputs:
  token:
    description: 'A valid github token for the organization'
    required: true
  org:
    description: 'The organization to use.'
    required: true
  team_slug:
    description: The team slug whose members you want to information for.
    required: true
outputs:
  stats:
    description: 'json object describing results.'
  stats_message:
    description: 'Single line message to summarize status for team members.'
runs:
  using: 'node12'
  main: 'index.js'