name: 'Github Team Open PR Summary'
description: 'Open PR counts for team members in specified org/team'
inputs:
  github_token:
    description: 'A valid github token for the organization'
    required: true
  org:
    description: 'The organization to use.'
    required: true
  team_slug:
    description: The team slug whose members you want to information for.
    required: true
  slack_token:
    description: A bot token with the correct scope
    required: true
  slack_channel:
    description: Channel identifier
    required: true
outputs:
  stats:
    description: 'json object describing results.'
runs:
  using: 'node12'
  main: 'index.js'